### Playground

This notebook is only for testing ideas or some dummy code

In [1]:
using Distributions

In [3]:
mean(Categorical(ones(4) ./ 4))

2.5

In [5]:
states = [ [ 1.0, 0.0 ], [ 0.0, 1.0 ] ]

2-element Vector{Vector{Float64}}:
 [1.0, 0.0]
 [0.0, 1.0]

In [25]:
estimated = [ Categorical(ones(2) ./ 2), Categorical(ones(2) ./ 2) ]

2-element Vector{Categorical{Float64, Vector{Float64}}}:
 Categorical{Float64, Vector{Float64}}(support=Base.OneTo(2), p=[0.5, 0.5])
 Categorical{Float64, Vector{Float64}}(support=Base.OneTo(2), p=[0.5, 0.5])

In [26]:
estimated_fl = [
    ForneyLab.ProbabilityDistribution(ForneyLab.Categorical, p = ones(2) ./ 2),
    ForneyLab.ProbabilityDistribution(ForneyLab.Categorical, p = ones(2) ./ 2)
]

2-element Vector{ForneyLab.ProbabilityDistribution{ForneyLab.Univariate, ForneyLab.Categorical}}:
 Cat(p=[0.50, 0.50])

 Cat(p=[0.50, 0.50])


In [27]:
average_mse(states, estimated_fl)

1.0

In [12]:
using ReactiveMPPaperExperiments

┌ Info: Precompiling ReactiveMPPaperExperiments [adcd1038-27e6-4580-819b-caa5dba07e45]
└ @ Base loading.jl:1342


In [9]:
import ForneyLab